### ISSUE TITLE
Did you try the input processing?

### ISSUE THREAD

**Issue by Edwardmark** [guyera/Generalized-ODIN-Implementation#2]
As above

**Comment by guyera** [comment]
I tried quite a few of them, and I unfortunately didn't see any
improvements from any of them for the most part. Random horizontal flips
showed a small improvement, but that's about it.

Alex.

**Comment by Edwardmark** [comment]
@guyera   What I mean about input preprocessing is 
![image](https://user-images.githubusercontent.com/15247551/101304242-cd82d080-387a-11eb-8941-ef2c519426ac.png)
not usual preprocessing.

**Comment by Edwardmark** [comment]
@guyera Did you try the gradient input preprocessing in test phase? Could you please public the test code？

**Comment by alexanderguyer** [comment]
Ah, I see what you're asking. This is already implemented in the test code, which is public. It is contained within cal.py: 
![image](https://user-images.githubusercontent.com/42660076/101531171-bbbb2f00-3947-11eb-9cff-c995440af95e.png)

It is very similar to [ODIN's](https://github.com/facebookresearch/odin/blob/master/code/calData.py) implementation of these input perturbations.

The code will be significantly refactored in the future, which will hopefully make details like this easier to find.

**Comment by Edwardmark** [comment]
Thanks. You help me a lot.
