### ISSUE TITLE
H head 

### ISSUE THREAD

**Issue by elv-zhounan** [guyera/Generalized-ODIN-Implementation#9]
Hi there, 
thanks for the helpful code!
I have one small question, can the h head be an angular margin head, like CosFace?
Thanks!

**Comment by guyera** [comment]
The h head is just supposed to be some sort of "similarity measure". The authors investigated the three implemented in this repo: inner product, negative [squared] euclidean distance, and cosine similarity. That isn't to say that these are the only three valid options. A lot of kernels would probably work, too.

I don't know anything about CosFace. Does it sound like it fits this intention?

**Comment by guyera** [comment]
Unless you encounter specific problems when running with an angular margin head, I don't think this issue needs to remain open. Feel free to open a new issue if that happens.
